name: Build qtbase-abi-5-15-13

on:
  workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:

      - name: Update Apt cache
        run: apt-get update -y

      - name: Install Basic Packages
        run: apt-get install -y git openssh-client reprepro gh apt-utils gpg build-essential devscripts

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}


      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace
    

      - uses: actions/checkout@v3

      - name: Build Package
        run: chmod +x ./qtbase-abi-5-15-13.sh && ./qtbase-abi-5-15-10.sh

#      - name: Commit changes back to git repository
#        uses: stefanzweifel/git-auto-commit-action@v4
